apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.apps.app }}
  name: {{ .Values.apps.app }}-svc
  namespace: {{ .Values.apps.namespace }}
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Values.apps.app }}
  type: NodePort
status:
  loadBalancer: {}
