apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.db.app }}
  name: {{ .Values.db.app }}-svc
  namespace: {{ .Values.db.namespace }}
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: {{ .Values.db.app }}
  type: NodePort
status:
  loadBalancer: {}
