apiVersion: v1
data:
  POSTGRES_DB: "Budgy_development"
  POSTGRES_PASSWORD: "arun"
  POSTGRES_USER: "arun"
  POSTGRES_HOST: "{{ .Values.db.app}}-svc"  
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
