db:
  app: "psql"
  namespace: "opt"
  replicas: 3
  image:
    repo: "docker.io/arunrascall/ruby-postgres"
    tag: "latest"
apps:
  app: "ruby"
  namespace: "opt"
  replicas: 4
  image:
    repo: "docker.io/arunrascall/ruby-web"
    tag: "latest"
secret:
  name: "app-cred"
  namespace: "opt"
    #user: "arun"
    #pass: "arun"
  db: "Budgy_latest"
