# rails-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - name: rails-container
          image: arunrascall/budget-rubyonrails:development
          env:
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_DB
              value: "Budgy_development"
            - name: POSTGRES_USER
              value: "arun"
            - name: POSTGRES_PASSWORD
              value: "arun"
          ports:
            - containerPort: 3000
          
---
# rails-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  selector:
    app: rails
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
