# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: arunrascall/budget-postgres:fixed
          env:
            - name: POSTGRES_DB
              value: "Budgy_development"
            - name: POSTGRES_USER
              value: "arun"
            - name: POSTGRES_PASSWORD
              value: "arun"
          ports:
            - containerPort: 5432
---
# postgres-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
