apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lab6a-svc-np
  name: lab6a-svc-np
  namespace: lab6a
spec:
  ports:
  - name: 31229-8080
    port: 31229
    protocol: TCP
    targetPort: 8080
  selector:
    app: lab6a-svc-np
  type: NodePort
status:
  loadBalancer: {}
