apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-budget-svc-np
  name: db-budget-svc-np
  namespace: ss
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db-budget
  type: NodePort
status:
  loadBalancer: {}
