apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rails-deploy
  name: rails-deploy
  namespace: new-ruby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rails-deploy
    spec:
      containers:
      - image: arunrascall/budget-rubyonrails:development
        name: budget-rubyonrails
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: db-config
              key: POSTGRES_HOST
        resources: {}
status: {}
