apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rails-svc
  name: rails-svc
  namespace: new-ruby
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: rails-svc
  type: NodePort
status:
  loadBalancer: {}
